#!/bin/bash
##
## Downloading directRNA data (from SG-Nex database)
## ------------------------------------------
##
#PBS -N log_s01
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q half_day
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## Clear any loaded modules and set the module directory
module purge
module use /apps/modules/all
##
## Stop the script execution on runtime errors
set -e
##
## Define the directRNA data directory and navigate to it
directRNA="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/directRNA/"
##
## Create the raw_data directory if it doesn't exist and navigate to it
mkdir -p "${directRNA}raw_data/"
cd "/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/directRNA/raw_data/"
##
## Download the SG-Nex directRNA FASTQ files using wget
echo "Starting data download"
echo ""

echo "H9_2_1 downloading"
wget --no-verbose https://sg-nex-data.s3.ap-southeast-1.amazonaws.com/data/sequencing_data_ont/fastq/SGNex_H9_directRNA_replicate2_run1/SGNex_H9_directRNA_replicate2_run1.fastq.gz
echo ""

echo "H9_3_1 downloading"
wget --no-verbose https://sg-nex-data.s3.ap-southeast-1.amazonaws.com/data/sequencing_data_ont/fastq/SGNex_H9_directRNA_replicate3_run1/SGNex_H9_directRNA_replicate3_run1.fastq.gz
echo ""

echo "H9_4_1 downloading"
wget --no-verbose https://sg-nex-data.s3.ap-southeast-1.amazonaws.com/data/sequencing_data_ont/fastq/SGNex_H9_directRNA_replicate4_run1/SGNex_H9_directRNA_replicate4_run1.fastq.gz
echo ""

echo "HEYA8_1_1 downloading"
wget --no-verbose https://sg-nex-data.s3.ap-southeast-1.amazonaws.com/data/sequencing_data_ont/fastq/SGNex_HEYA8_directRNA_replicate1_run1/SGNex_HEYA8_directRNA_replicate1_run1.fastq.gz
echo ""

echo "HEYA8_2_1 downloading"
wget --no-verbose https://sg-nex-data.s3.ap-southeast-1.amazonaws.com/data/sequencing_data_ont/fastq/SGNex_HEYA8_directRNA_replicate2_run1/SGNex_HEYA8_directRNA_replicate2_run1.fastq.gz
echo ""

echo "HEYA8_3_3 downloading"
wget --no-verbose https://sg-nex-data.s3.ap-southeast-1.amazonaws.com/data/sequencing_data_ont/fastq/SGNex_HEYA8_directRNA_replicate3_run1/SGNex_HEYA8_directRNA_replicate3_run1.fastq.gz
##
echo ""
echo "Done"
echo ""
date  # Print the current date and time
echo ""
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
