#!/bin/bash
##
## Running NanoPlot on the downsized cDNA data set
## ------------------------------------------
##
#PBS -N log_s05
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q one_day
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## Clear any loaded modules and set the module directory
module purge
module use /apps/modules/all
##
## Stop the script execution on runtime errors
set -e
##
## Load required modules
module load Miniconda3/22.11.1-1
##
## Activate nanopack_env environment
source /apps/software/Miniconda3/22.11.1-1/bin/activate nanopack_env
##
## Check NanoPlot version
NanoPlot --version
echo ""
##
## Set up folder pathways for input and output
cDNA="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/cDNA/downsized_data/"
QC="/mnt/beegfs/home/s445216/thesis_project/ONP/results/QC_results/cDNA/nonfilt/NanoPlot/"
##
## Define input file paths
H9_2_4="${cDNA}SGNex_H9_cDNA_replicate2_run4_down.fastq.gz"
H9_3_4="${cDNA}SGNex_H9_cDNA_replicate3_run4_down.fastq.gz"
H9_4_4="${cDNA}SGNex_H9_cDNA_replicate4_run4_down.fastq.gz"
HEYA8_1_4="${cDNA}SGNex_HEYA8_cDNA_replicate1_run4_down.fastq.gz"
HEYA8_2_4="${cDNA}SGNex_HEYA8_cDNA_replicate2_run4_down.fastq.gz"
HEYA8_3_3="${cDNA}SGNex_HEYA8_cDNA_replicate3_run3_down.fastq.gz"
##
## Define output directories and create them if they don't exist
H9_2_4_out="${QC}H9_2_4/"
mkdir -p "${H9_2_4_out}"
##
H9_3_4_out="${QC}H9_3_4/"
mkdir -p "${H9_3_4_out}"
##
H9_4_4_out="${QC}H9_4_4/"
mkdir -p "${H9_4_4_out}"
##
HEYA8_1_4_out="${QC}HEYA8_1_4/"
mkdir -p "${HEYA8_1_4_out}"
##
HEYA8_2_4_out="${QC}HEYA8_2_4/"
mkdir -p "${HEYA8_2_4_out}"
##
HEYA8_3_3_out="${QC}HEYA8_3_3/"
mkdir -p "${HEYA8_3_3_out}"
##
## Run NanoPlot on each FASTQ file and generate plots
echo "Making plots for H9_2_4"
NanoPlot --fastq "${H9_2_4}" --threads 12 --drop_outliers --outdir "${H9_2_4_out}"
echo ""
##
echo "Making plots for H9_3_4"
NanoPlot --fastq "${H9_3_4}" --threads 12 --drop_outliers --outdir "${H9_3_4_out}"
echo ""
##
echo "Making plots for H9_4_4"
NanoPlot --fastq "${H9_4_4}" --threads 12 --drop_outliers --outdir "${H9_4_4_out}"
echo ""
##
echo "Making plots for HEYA8_1_4"
NanoPlot --fastq "${HEYA8_1_4}" --threads 12 --drop_outliers --outdir "${HEYA8_1_4_out}"
echo ""
##
echo "Making plots for HEYA8_2_4"
NanoPlot --fastq "${HEYA8_2_4}" --threads 12 --drop_outliers --outdir "${HEYA8_2_4_out}"
echo ""
##
echo "Making plots for HEYA8_3_3"
NanoPlot --fastq "${HEYA8_3_3}" --threads 12 --drop_outliers --outdir "${HEYA8_3_3_out}"
echo ""
##
echo "Done"
echo ""
date  # Print the current date and time
echo ""
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
