#!/bin/bash
##
## Filtering the downsized data using chopper
## ------------------------------------------
##
#PBS -N log_s06
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q one_day
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## Clear any loaded modules and set the module directory
module purge
module use /apps/modules/all
##
## Stop the script execution on runtime errors
set -e
##
## Load required modules
module load Miniconda3/22.11.1-1
##
## Activate chopper_env environment
source /apps/software/Miniconda3/22.11.1-1/bin/activate chopper_env
##
## Check chopper version
chopper --version
echo ""
##
## Set up folder pathways
downsize="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/cDNA/downsized_data/"
filt="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/cDNA/filtered_data/"
mkdir -p "${filt}"
cd "${downsize}"
##
## Run chopper to filter the fastq files
echo "Filtering H9_2_4"
gunzip -c "SGNex_H9_cDNA_replicate2_run4_down.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "SGNex_H9_cDNA_replicate2_run4_filt.fastq.gz"
echo ""
##
echo "Filtering H9_3_4"
gunzip -c "SGNex_H9_cDNA_replicate3_run4_down.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "SGNex_H9_cDNA_replicate3_run4_filt.fastq.gz"
echo ""
##
echo "Filtering H9_4_4"
gunzip -c "SGNex_H9_cDNA_replicate4_run4_down.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "SGNex_H9_cDNA_replicate4_run4_filt.fastq.gz"
echo ""
##
echo "Filtering HEYA8_1_4"
gunzip -c "SGNex_HEYA8_cDNA_replicate1_run4_down.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "SGNex_HEYA8_cDNA_replicate1_run4_filt.fastq.gz"
echo ""
##
echo "Filtering HEYA8_2_4"
gunzip -c "SGNex_HEYA8_cDNA_replicate2_run4_down.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "SGNex_HEYA8_cDNA_replicate2_run4_filt.fastq.gz"
echo ""
##
echo "Filtering HEYA8_3_3"
gunzip -c "SGNex_HEYA8_cDNA_replicate3_run3_down.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "SGNex_HEYA8_cDNA_replicate3_run4_filt.fastq.gz"
echo ""
##
# Check the result
ls -all
echo ""
##
# Move filtered files to the filtered folder
echo "Moving filtered data"
mv *filt.fastq.gz "${filt}"
echo ""
##
echo
echo "Done"
echo
date
echo
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
