#!/bin/bash
##
## Downloading EPI2ME wf_transcriptomes pipeline script (with NextFlow)
## ------------------------------------------
##
##"EPI2ME-sub2024v1"
##
#PBS -N s04_downsize_data
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q three_hour
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## Use the modules container (with NextFlow and EPI2ME)
module purge
module use /apps/modules/all
##
## Stop at run time errors
set -e
##
## Load required modules
module load seqtk/1.4-GCC-12.3.0
##
## Set up folder pathways
downsize="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/downsized_data/"
fullsize="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/full_data/"

cd "{downsize}"
cp -r "{fullsize}"/cDNA/ cDNA/
cp -r "{fullsize}"/directRNA/ directRNA/

cDNA="{downsize}"/cDNA/differential_expression/
directRNA="{downsize}"/directRNA/differential_expression/
##
## Downsize cDNA data
cd "${cDNA}"/barcode01
seqtk sample -s100 SGNex_H9_cDNA_replicate2_run4.fastq.gz 0.1 | gzip > SGNex_H9_cDNA_replicate2_run4.fastq.gz

cd "${cDNA}"/barcode02
seqtk sample -s100 SGNex_H9_cDNA_replicate3_run4.fastq.gz 0.1 | gzip > SGNex_H9_cDNA_replicate3_run4.fastq.gz

cd "${cDNA}"/barcode03
seqtk sample -s100 SGNex_H9_cDNA_replicate4_run4.fastq.gz 0.1 | gzip > SGNex_H9_cDNA_replicate4_run4.fastq.gz

cd "${cDNA}"/barcode04
seqtk sample -s100 SGNex_H9_cDNA_replicate2_run4.fastq.gz 0.1 | gzip > SGNex_H9_cDNA_replicate2_run4.fastq.gz

cd "${cDNA}"/barcode05
seqtk sample -s100 SGNex_H9_cDNA_replicate2_run4.fastq.gz 0.1 | gzip > SGNex_H9_cDNA_replicate2_run4.fastq.gz

cd "${cDNA}"/barcode06
seqtk sample -s100 SGNex_H9_cDNA_replicate2_run4.fastq.gz 0.1 | gzip > SGNex_H9_cDNA_replicate2_run4.fastq.gz
##
## Downsize directRNA data
cd "${directRNA}"/barcode01
seqtk sample -s100 SGNex_H9_directRNA_replicate2_run1.fastq.gz 0.1 | gzip > SGNex_H9_directRNA_replicate2_run1.fastq.gz

cd "${directRNA}"/barcode02
seqtk sample -s100 SGNex_H9_directRNA_replicate3_run1.fastq.gz 0.1 | gzip > SGNex_H9_directRNA_replicate3_run1.fastq.gz

cd "${directRNA}"/barcode03
seqtk sample -s100 SGNex_H9_directRNA_replicate4_run1.fastq.gz 0.1 | gzip > SGNex_H9_directRNA_replicate4_run1.fastq.gz

cd "${directRNA}"/barcode04
seqtk sample -s100 SGNex_HEYA8_directRNA_replicate1_run1.fastq.gz 0.1 | gzip > SGNex_HEYA8_directRNA_replicate1_run1.fastq.gz

cd "${directRNA}"/barcode05
seqtk sample -s100 SGNex_HEYA8_directRNA_replicate2_run1.fastq.gz 0.1 | gzip > SGNex_HEYA8_directRNA_replicate2_run1.fastq.gz

cd "${directRNA}"/barcode06
seqtk sample -s100 SGNex_HEYA8_directRNA_replicate3_run1.fastq.gz 0.1 | gzip > SGNex_HEYA8_directRNA_replicate3_run1.fastq.gz
##
echo
echo "Completed Downsizing script"
echo
date
echo
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
