#!/bin/bash
##
## Downloading EPI2ME wf_transcriptomes pipeline script (with NextFlow)
## ------------------------------------------
##
##"EPI2ME-sub2024v1"
##
#PBS -N s04a_NanoComp_cDNA
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q three_hour
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
module purge
module use /apps/modules/all
##
## Stop at run time errors
set -e
##
## Load required modules
module load Miniconda3/22.11.1-1
##
## Create environment and install nanopack
cd /mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/full_data/cDNA/quality_control/
source /apps/software/Miniconda3/22.11.1-1/bin/activate nanopack_env
##
## Versions
NanoComp --version
echo ""
##
## Set up folder pathways
quality_control="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/full_data/cDNA/quality_control/"
cDNA="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/full_data/cDNA/differential_expression/"
##
barcode01="${cDNA}"barcode01/SGNex_H9_cDNA_replicate2_run4.fastq.gz
barcode02="${cDNA}"barcode02/SGNex_H9_cDNA_replicate3_run4.fastq.gz
barcode03="${cDNA}"barcode03/SGNex_H9_cDNA_replicate4_run4.fastq.gz
barcode04="${cDNA}"barcode04/SGNex_HEYA8_cDNA_replicate1_run4.fastq.gz
barcode05="${cDNA}"barcode05/SGNex_HEYA8_cDNA_replicate2_run4.fastq.gz
barcode06="${cDNA}"barcode06/SGNex_HEYA8_cDNA_replicate3_run4.fastq.gz
##
nanocomp_folder="${quality_control}"/NanoComp
##
## Run nanopack on the fastq files
echo "Comparing samples"
echo ""
NanoComp \
--fastq "${barcode01}" "${barcode02}" "${barcode03}" "${barcode04}" "${barcode05}" "${barcode06}" \
--names H9_a H9_b H9_c HEYA8_a HEYA8_b HEYA8_c \
--threads 12 \
--outdir "${nanocomp_folder}"
##
echo
echo "Completed NanoComp cDNA script"
echo
date
echo
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
