#!/bin/bash
##
## Downloading EPI2ME wf_transcriptomes pipeline script (with NextFlow)
## ------------------------------------------
##
##"EPI2ME-sub2024v1"
##
#PBS -N s04b_NanoComp_RNA
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q three_hour
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
module purge
module use /apps/modules/all
##
## Stop at run time errors
set -e
##
## Load required modules
module load Miniconda3/22.11.1-1
##
## Create environment and install nanopack
cd /mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/full_data/cDNA/quality_control/
source /apps/software/Miniconda3/22.11.1-1/bin/activate chopper_env
##
## Versions
chopper --version
echo ""
##
## Set up folder pathways
RNA="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/full_data/directRNA/differential_expression/"
##
barcode01="${RNA}"barcode01
barcode02="${RNA}"barcode02
barcode03="${RNA}"barcode03
barcode04="${RNA}"barcode04
barcode05="${RNA}"barcode05
barcode06="${RNA}"barcode06
##
## Run nanopack on the fastq files
echo "Filtering barcode01"
gunzip -c "${barcode01}/SGNex_H9_directRNA_replicate2_run1.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "${barcode01}/SGNex_H9_directRNA_replicate2_run1_filt.fastq.gz"

echo "Filtering barcode02"
gunzip -c "${barcode02}/SGNex_H9_directRNA_replicate3_run1.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "${barcode02}/SGNex_H9_directRNA_replicate3_run1_filt.fastq.gz"

echo "Filtering barcode03"
gunzip -c "${barcode03}/SGNex_H9_directRNA_replicate4_run1.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "${barcode03}/SGNex_H9_directRNA_replicate4_run1_filt.fastq.gz"

echo "Filtering barcode04"
gunzip -c "${barcode04}/SGNex_HEYA8_directRNA_replicate1_run1.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "${barcode04}/SGNex_HEYA8_directRNA_replicate1_run1_filt.fastq.gz"

echo "Filtering barcode05"
gunzip -c "${barcode05}/SGNex_HEYA8_directRNA_replicate2_run1.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "${barcode05}/SGNex_HEYA8_directRNA_replicate2_run1_filt.fastq.gz"

echo "Filtering barcode01"
gunzip -c "${barcode06}/SGNex_HEYA8_directRNA_replicate3_run1.fastq.gz" | chopper -q 10 --minlength 500 --maxlength 15000 | gzip > "${barcode06}/SGNex_HEYA8_directRNA_replicate3_run1_filt.fastq.gz"
##
echo
echo "Completed NanoComp RNA script"
echo
date
echo
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
