#!/bin/bash
##
## Downsizing the full cDNA data set
## ------------------------------------------
##
#PBS -N log_s03
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q one_day
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## Clear any loaded modules and set the module directory
module purge
module use /apps/modules/all
##
## Stop the script execution on runtime errors
set -e
##
## Load required modules
module load seqtk/1.4-GCC-12.3.0
##
## Set up folder pathways
downsize="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/cDNA/downsized_data/"
fullsize="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/cDNA/raw_data/"
##
mkdir -p "${downsize}"
cd "${fullsize}"
##
## Define input files
files=("SGNex_H9_cDNA_replicate2_run4" "SGNex_H9_cDNA_replicate3_run4" "SGNex_H9_cDNA_replicate4_run4" "SGNex_HEYA8_cDNA_replicate1_run4" "SGNex_HEYA8_cDNA_replicate2_run4" "SGNex_HEYA8_cDNA_replicate3_run3")
##
## Downsize cDNA data
for file in "${files[@]}"; do
    echo "Downsizing $file"
    seqtk sample -s100 ${fullsize}${file}.fastq.gz 0.1 | gzip > ${file}_down.fastq.gz
    echo ""
done
##
# Check the result
ls -all
echo ""
##
# Move downsized files to the downsized folder
echo "Moving downsized data"
mv *down.fastq.gz "${downsize}"
echo ""
##
echo ""
echo "Done"
echo ""
date
echo ""
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
