#!/bin/bash
##
## Running NanoComp on the filtered cDNA data set
## ------------------------------------------
##
#PBS -N log_s07
##
#PBS -l select=1:ncpus=4:mpiprocs=4
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q one_day
##
#PBS -m abe 
#PBS -M molly.romanis.216@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## Clear any loaded modules and set the module directory
module purge
module use /apps/modules/all
##
## Stop the script execution on runtime errors
set -e
##
## Load required modules
module load Miniconda3/22.11.1-1
##
## Activate nanopack_env environment
source /apps/software/Miniconda3/22.11.1-1/bin/activate nanopack_env
##
## NanoComp version
NanoComp --version
echo ""
##
## Define the cDNA data directory and navigate to it
cDNA="/mnt/beegfs/home/s445216/thesis_project/ONP/SG-Nex_data/cDNA/filtered_data/"
##
QC="/mnt/beegfs/home/s445216/thesis_project/ONP/results/QC_results/cDNA/filt/NanoComp/"
mkdir -p "${QC}"
##
# Set source fastq files and corresponding samples names
H9_2_4="${cDNA}SGNex_H9_cDNA_replicate2_run4_filt.fastq.gz"
H9_3_4="${cDNA}SGNex_H9_cDNA_replicate3_run4_filt.fastq.gz"
H9_4_4="${cDNA}SGNex_H9_cDNA_replicate4_run4_filt.fastq.gz"
HEYA8_1_4="${cDNA}SGNex_HEYA8_cDNA_replicate1_run4_filt.fastq.gz"
HEYA8_2_4="${cDNA}SGNex_HEYA8_cDNA_replicate2_run4_filt.fastq.gz"
HEYA8_3_3="${cDNA}SGNex_HEYA8_cDNA_replicate3_run3_filt.fastq.gz"
##
# Run NanoComp
echo "Comparing samples"
echo ""
NanoComp \
--fastq "${H9_2_4}" "${H9_3_4}" "${H9_4_4}" "${HEYA8_1_4}" "${HEYA8_2_4}" "${HEYA8_3_3}" \
--names H9_2_4 H9_3_4 H9_4_4 HEYA8_1_4 HEYA8_2_4 HEYA8_3_3 \
--threads 12 \
--outdir "${QC}"
##
echo ""
echo "Done"
echo ""
date
echo ""
##
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
